### ISSUE TITLE
Conflicting pilots

### ISSUE THREAD

**Issue by SneakyGitau** [Patschke/xwing#19]
Hi Patschke, looks like there is still an issue with the Xi-shuttle quickbuild, I think it's because Commander Malarus is a Tie/FO pilot a Xi-shuttle pilot and a crew card. If you pick the Xi-shuttle then change to say First order courier then change back to Commander Malarus she's gone from being in a Xi-shuttle to a Tie/FO.

**Comment by SneakyGitau** [comment]
![malarus](https://user-images.githubusercontent.com/48877186/99186950-c0e4ee00-278e-11eb-9db6-c7c0c4f4571b.jpg)

**Comment by Patschke** [comment]
Ah. Well, it's the same issue as for Gideon Hask (in case you are interested: in the same file somwhere above the pilot names are defined - and for Malarus it is either "Commander Malarus" for the TIE/fo (line 6156) or "Commander Malarus (Xi Shuttle)" for the Shuttle version (line 8464). Upgrades are different from pilots, so having an upgrade and pilot with the same name is fine). 

Gonna fix it, thanks for pointing it out again.
