### ISSUE TITLE
Phrase translation

### ISSUE THREAD

**Issue by iwazaru** [Patschke/xwing#9]
Phrase translations are difficult in french without the context (spelling may varies depending on the context). The only help I can get is the german translations and unfortunately I didn’t practice german a lot since high school :) although it helped me guess that « SMALL » should be translated to « Vaisseau petit » and not « petit ». Maybe adding the english translations or even better, some comments to provide context would help?

**Comment by Patschke** [comment]
json does not support comments, but I can try to add them
